### ISSUE TITLE
Errors found while checking this document as XHTML 1.0 Transitional!

### ISSUE THREAD

**Issue by silabsoft** [fracek/better-github-widget#1]
This widget is great however it does have two small markup issues I wanted to point out
1. required attribute "alt" not specified  - the issue is on the octocat image it has no alt tag, its important to have incase the image cannot be displayed.

Fixed code:
        // Octocat image
        echo '<img width="128px" src="' . plugins_url('octocat.png', __FILE__) . '"';
        echo ' style="display: block; margin: 0px auto;" alt= "github octocat"/>';
1.  end tag for element "a" which is not open - In your code you closed the link to the users github profile and then closed the a tag again after displaying the username.

**Comment by fracek** [comment]
I fixed this, I will upload the new version to wordpress.org as soon as possible.

Thank you
