### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by cfoellmann** [fracek/better-github-widget#14]
what is the license? Should be added to all readme files and the header of the php

**Comment by fracek** [comment]
The license is in the LICENSE.txt file, I adde a notice in both the README.md and the readme.txt files in commit f126f385d4adc46d5f246247c67aec6d47098ba8

I won't add a license block at the beginning of each file because I hate it, sorry.

**Comment by cfoellmann** [comment]
I hate the license block, too ;-)

I meant this: (better-github-widget.php)

```
Plugin Name: Better GitHub Widget
Plugin URI: https://wordpress.org/extend/plugins/better-github-widget/
Description: Display your GitHub projects
Author: Francesco Ceccon
Version: 0.6.1
Author URI: http://francesco-cek.com
License: BSD 2-clause
License URI: https://raw.github.com/fracek/better-github-widget/master/LICENSE.txt
```

**Comment by fracek** [comment]
OK, I added the license info to the php file too.
