### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by cfoellmann** [fracek/better-github-widget#18]
I don't want to offend you but I just looked through my open GH issues and re-found your little WP plugin.

Current status:
- Due to its age it is hidden from WP-Admin > Add Plugin

- If you upload the current version from wp.org it will error out on activation on a current WP install

Maybe you should consider closing the plugin on wp.org?

Cheers,
Chris

**Comment by fracek** [comment]
Hi Chris,

yep, I completely forgot I made this. I emailed plugins@wordpress.org asking them to remove it.

**Comment by fracek** [comment]
The plugin has been removed. Thanks again for reminding me!

**Comment by cfoellmann** [comment]
thanks for not being offended. I am just in a cleanup sprint 😃
