### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by cfoellmann** [fracek/better-github-widget#6]
Hi guys,

just register @ https://translate.foe-services.de/projects/better-github-widget so I can make you a admin for the project so we can translate it to more languages

Christian

**Comment by fracek** [comment]
Ok, I registered.

If you can add a small how-to I will translate it to italian.

**Comment by cfoellmann** [comment]
https://translate.foe-services.de/projects/better-github-widget/it/it just double click the string and translate in the textarea.

The software is still in development so some functions are not yet implemented.
When everything is translated, make sure you are on the page "all" and click export on the bottom. Note: .po export is working, .mo export is broken at the moment. :-( Use this in the .po http://tools.konstruktors.com/

**Comment by fracek** [comment]
Ok, I did it and it worked (I think).

I see you work there so thank you again :)

**Comment by cfoellmann** [comment]
Sweet :-)
The platform still needs some work but its on a good way and I am going to give you some more far reaching permissions as soon as possible.
